name: charliesheets
favicon: null
layout_spectrum: 0.19281277456320822
typography_spectrum: 0.2642180814873427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8887693432625383
  lightness: 0.4477782140020281
  saturation: 0.3337562505621463
  rhythmicContrast: 0.8389794754330069
purpose: []
